### ISSUE TITLE
haproxy-confd failing with "WARNING Skipping confd config file."

### ISSUE THREAD

**Issue by michielbdejong** [indiehosters/indiehosters#49]
Right now on my server I'm seeing "WARNING Skipping confd config file." in `systemctl status haproxy-confd` and I don't understand why this is happening, or how to investigate it further.

Work-around: whenever you add or change a backend, update /data/runtime/haproxy/haproxy.cfg manually and run `systemctl restart haproxy` manually.

**Comment by pierreozoux** [comment]
This is totally normal in fact:
https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md

(I will switch other issues to my repo)
