### ISSUE TITLE
IaaS providers

### ISSUE THREAD

**Issue by michielbdejong** [indiehosters/indiehosters#52]
Scaleway is 30% cheaper than Vultr for a 2Gb-ram server, and it has 50Gb-ssd instead of 40Gb-ssd. Also, it's easy to add volumes to it, in case you have a few ownCloud or Cozy users that use a lot of space, you can mount in a 50Gb volume for them, for 2 eur/month. At that price, we could even say that up to 50Gb we don't bill extra (because only a small percentage of users will use more than 1Gb anyway)

**Comment by pierreozoux** [comment]
Is it: https://www.scaleway.com/pricing

Do you have a referal code?

Did yo see that it is ARM? (It has some limitations, like no Mongo for instance.)
I don't know about docker on arm for now... But the storage part is interesting. But for now, if you have a client that require 300GB, you can't on there infra. But thanks for the hint, we have to look at it, it looks promising :)

**Comment by michielbdejong** [comment]
Ah right, I had confused "ARM" with "AMD"! :) Yes, that's not so practical for us, then.
